import { io } from 'socket.io-client';
import pg from './backend/node_modules/pg/lib/index.js';
import dotenv from './backend/node_modules/dotenv/lib/main.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__dirname, 'backend', '.env') });

const { Pool } = pg;
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

async function testViabilityHandoffFlow() {
  console.log('========================================================================');
  console.log('🧪 VERIFYING VIABILITY ASSESSMENT -> URBAN WASTE MATCHER HANDOFF FLOW');
  console.log('========================================================================');

  let errors = 0;

  // 1. Establish real-time socket connections for multi-user sync
  console.log('\n[Step 1] Establishing Real-Time Socket Connection...');
  const buyerSocket = io('http://localhost:5000', { transports: ['websocket', 'polling'] });
  await new Promise((resolve) => buyerSocket.on('connect', resolve));
  console.log('  ✅ Buyer socket connected:', buyerSocket.id);

  const receivedSocketEvents = [];
  buyerSocket.on('listing:created', (data) => {
    console.log('  📡 [Buyer Socket] Received real-time listing:created event:', data.id, 'linked to assessment:', data.source_assessment_id);
    receivedSocketEvents.push(data);
  });

  // 2. Simulate Viability Scanner Field Assessment Result
  const mockAssessmentId = `fa_scan_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  console.log('\n[Step 2] Simulating Viability Assessment completed on device...');
  console.log('  Generated Assessment ID:', mockAssessmentId);

  // 3. Construct Handoff Payload as generated by createHandoffFromAssessment()
  const handoffPayload = {
    source: "viability-scanner",
    destination: "urban-waste-matcher",
    assessmentId: mockAssessmentId,
    crop: "Tomato",
    condition: "high",
    conditionQuality: "damaged",
    mappedCondition: "damaged",
    cultivatedAcres: 2.5,
    quantity: { value: null, unit: "kg" }, // Simulates scan without pre-entered commercial quantity
    readableLocation: "Alanganallur, Madurai, Tamil Nadu",
    askingPrice: null,
    selectedImage: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAP...",
    recommendation: {
      pathway: "Urban Waste Matcher",
      action: "List on Urban Waste Matcher for off-take",
      reason: "High disease damage suitable for commercial processing off-take"
    }
  };

  // 4. Simulate WasteMarket receiving handoff and submitting
  console.log('\n[Step 3] Simulating Urban Waste Matcher form submission with handoff data...');
  const newPostId = `wp_handoff_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
  
  // Sanitized values as applied by fixed WasteMarket.jsx & marketplaceService.js
  const parsedQty = Number(handoffPayload.quantity?.value);
  const quantityKg = (!isNaN(parsedQty) && parsedQty >= 0.1) ? parsedQty : 100;
  const parsedPrice = Number(handoffPayload.askingPrice);
  const askingPrice = (!isNaN(parsedPrice) && parsedPrice >= 0) ? parsedPrice : 0;

  const marketplacePostPayload = {
    id: newPostId,
    creator_id: "usr_farmer_ramesh_01",
    creator_role: "farmer",
    crop_type: handoffPayload.crop || "Tomato",
    quantity_kg: quantityKg,
    condition: handoffPayload.mappedCondition || "damaged",
    location: handoffPayload.readableLocation || "Madurai, Tamil Nadu",
    asking_price: askingPrice,
    image_url: handoffPayload.selectedImage,
    source_assessment_id: handoffPayload.assessmentId,
    title: `${handoffPayload.crop} Crop Waste`,
    farmer_name: "Ramesh Patel",
    contact_phone: "9876543210"
  };

  console.log('  Posting to Vite Proxy URL: http://localhost:5173/api/v1/marketplace/listings');
  console.log('  Payload Details:', {
    id: marketplacePostPayload.id,
    creator_id: marketplacePostPayload.creator_id,
    crop_type: marketplacePostPayload.crop_type,
    quantity_kg: marketplacePostPayload.quantity_kg,
    condition: marketplacePostPayload.condition,
    location: marketplacePostPayload.location,
    source_assessment_id: marketplacePostPayload.source_assessment_id,
    imagePresent: Boolean(marketplacePostPayload.image_url),
    imageLength: marketplacePostPayload.image_url?.length
  });

  const response = await fetch('http://localhost:5173/api/v1/marketplace/listings', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(marketplacePostPayload)
  });

  const responseJson = await response.json();
  console.log('\n[Step 4] Inspecting Server Response:');
  console.log('  HTTP Status:', response.status, response.statusText);
  console.log('  Response Body:', responseJson);

  if (response.status === 201 && responseJson.status === 'success') {
    console.log('  ✅ SUCCESS: HTTP 201 Created returned!');
  } else {
    console.error('  ❌ FAILED: Unexpected status code', response.status);
    errors++;
  }

  // 5. Wait for Socket.IO event propagation
  await new Promise(r => setTimeout(r, 600));

  console.log('\n[Step 5] Checking Real-Time Broadcast to other users...');
  const receivedEvent = receivedSocketEvents.find(e => e.id === newPostId);
  if (receivedEvent && receivedEvent.source_assessment_id === mockAssessmentId) {
    console.log('  ✅ Real-time broadcast received with source_assessment_id:', receivedEvent.source_assessment_id);
  } else {
    console.error('  ❌ Socket event not received or missing source_assessment_id');
    errors++;
  }

  // 6. Verify PostgreSQL Database Persistence & Foreign Key linkage
  console.log('\n[Step 6] Verifying PostgreSQL Database Persistence...');
  const listingRes = await pool.query('SELECT * FROM marketplace_listings WHERE id = $1', [newPostId]);
  const assessmentRes = await pool.query('SELECT * FROM field_assessments WHERE id = $1', [mockAssessmentId]);

  if (listingRes.rows.length === 1) {
    const row = listingRes.rows[0];
    console.log('  ✅ marketplace_listings row:');
    console.log('     ID:', row.id);
    console.log('     Creator ID:', row.creator_id);
    console.log('     Crop Type:', row.crop_type);
    console.log('     Quantity (kg):', row.quantity_kg);
    console.log('     Source Assessment ID:', row.source_assessment_id);
    console.log('     Created At:', row.created_at);
  } else {
    console.error('  ❌ Listing not found in PostgreSQL marketplace_listings table');
    errors++;
  }

  if (assessmentRes.rows.length === 1) {
    const aRow = assessmentRes.rows[0];
    console.log('  ✅ field_assessments row (FK satisfied):');
    console.log('     ID:', aRow.id);
    console.log('     User ID:', aRow.user_id);
    console.log('     Crop Name:', aRow.crop_name);
  } else {
    console.error('  ❌ Assessment record missing from field_assessments');
    errors++;
  }

  // 7. Verify GET /api/v1/marketplace/listings contains the linked listing
  console.log('\n[Step 7] Checking GET /api/v1/marketplace/listings shared feed...');
  const getRes = await fetch('http://localhost:5173/api/v1/marketplace/listings');
  const getJson = await getRes.json();
  const foundListing = getJson.data?.find(l => l.id === newPostId);
  if (foundListing && foundListing.source_assessment_id === mockAssessmentId) {
    console.log('  ✅ Listing found in shared feed with active source_assessment_id link');
  } else {
    console.error('  ❌ Listing missing from shared feed');
    errors++;
  }

  // 8. Clean up test records
  console.log('\n[Step 8] Cleaning up test records...');
  await pool.query('DELETE FROM marketplace_listings WHERE id = $1', [newPostId]);
  await pool.query('DELETE FROM field_assessments WHERE id = $1', [mockAssessmentId]);
  console.log('  ✅ Test data cleaned up');

  buyerSocket.disconnect();
  await pool.end();

  console.log('\n========================================================================');
  if (errors === 0) {
    console.log('🎉 ALL VIABILITY ASSESSMENT -> URBAN WASTE MATCHER HANDOFF TESTS PASSED (0 errors)');
  } else {
    console.log(`❌ FAILED WITH ${errors} ERRORS`);
  }
  console.log('========================================================================');
}

testViabilityHandoffFlow().catch(console.error);
