/**
 * AgroCycle Smart Logistics & Load Consolidation Service
 *
 * Deterministic engine for agricultural freight consolidation:
 * 1. Multi-farmer demand aggregation
 * 2. Geographic proximity clustering (Haversine distance)
 * 3. Vehicle capacity & utilization optimization
 * 4. Deterministic nearest-neighbour pickup -> delivery route generation
 * 5. Proportional transport cost allocation
 * 6. Farmer Net Expected Value integration
 * 7. Offline-first persistence in IndexedDB / localDB
 * 8. Driver trip execution state machine
 *
 * CRITICAL ARCHITECTURAL PRINCIPLES:
 * - 100% DETERMINISTIC: All matching, clustering, routing, costs, and net values are computed mathematically.
 * - ZERO LLM FABRICATION: Calculation results are never generated by LLMs.
 * - ESTIMATED VALUES: All distances and costs are explicitly labeled as estimated.
 * - NO EXTERNAL GPS / MAPS APIS: Uses simulated coordinates and Haversine straight-line distance.
 */

import { localDB, KEYS } from "./localDB.js";
import { normalizeCropName, KNOWN_CROP_ALIASES } from "./marketPriceService.js";
import { enqueueAction, ACTION_TYPES } from "./syncQueue.js";
import { syncManager } from "./syncManager.js";

// ==============================================================================
// CONFIGURATION & CONSTANTS
// ==============================================================================

export const MAX_PICKUP_CLUSTER_DISTANCE_KM = 25; // Default configurable clustering radius (km)
export const DEFAULT_TRANSPORT_RATE_PER_KM = 60; // Default configurable vehicle transport rate (₹/km)

export const SHIPMENT_STATUS = {
  MATCHED: "MATCHED",
  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED"
};

export const VEHICLE_TYPES = {
  SMALL_PICKUP: "Small Pickup (1-2 Ton)",
  MEDIUM_TRUCK: "Medium Truck (3-6 Ton)",
  HEAVY_TRUCK: "Heavy Truck (10-15 Ton)",
  REEFER_TRUCK: "Refrigerated Van"
};

export const DRIVER_STATUS = {
  AVAILABLE: "AVAILABLE",
  ON_TRIP: "ON_TRIP",
  OFFLINE: "OFFLINE"
};

// ==============================================================================
// 1. HAVERSINE DISTANCE UTILITY
// ==============================================================================

/**
 * Calculates great-circle distance between two GPS coordinates in kilometers (Haversine formula).
 * Clearly marked as approximate straight-line estimated distance.
 *
 * @param {number} lat1
 * @param {number} lon1
 * @param {number} lat2
 * @param {number} lon2
 * @returns {number|null} Estimated distance in km rounded to 2 decimal places, or null if invalid.
 */
export function calculateHaversineDistanceKm(lat1, lon1, lat2, lon2) {
  if (
    typeof lat1 !== "number" || isNaN(lat1) ||
    typeof lon1 !== "number" || isNaN(lon1) ||
    typeof lat2 !== "number" || isNaN(lat2) ||
    typeof lon2 !== "number" || isNaN(lon2)
  ) {
    return null;
  }

  const R = 6371; // Earth's radius in km
  const toRad = (deg) => (deg * Math.PI) / 180;

  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);

  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) *
    Math.sin(dLon / 2) * Math.sin(dLon / 2);

  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  const distance = R * c;

  return Math.round(distance * 100) / 100;
}

// Alias for explicit naming requirement
export const distanceKm = calculateHaversineDistanceKm;

// ==============================================================================
// 2. FARMER FILTERING
// ==============================================================================

/**
 * Filters available farmers compatible with the buyer's commodity requirement.
 *
 * @param {Array} farmers - List of farmer records
 * @param {Object} buyerDemand - Buyer requirement object
 * @returns {Array} List of matching farmers
 */
export function filterCompatibleFarmers(farmers = [], buyerDemand = {}) {
  if (!Array.isArray(farmers) || !buyerDemand || !buyerDemand.crop) {
    return [];
  }

  const demandCropNorm = normalizeCropName(buyerDemand.crop);
  const demandCanonical = KNOWN_CROP_ALIASES[demandCropNorm] || demandCropNorm;

  return farmers.filter((farmer) => {
    if (!farmer || typeof farmer !== "object") return false;

    // 1. Crop Match
    const fCropNorm = normalizeCropName(farmer.crop || farmer.crop_type || farmer.commodity || "");
    const fCanonical = KNOWN_CROP_ALIASES[fCropNorm] || fCropNorm;
    if (fCanonical !== demandCanonical) return false;

    // 2. Quantity Available > 0
    const qty = Number(farmer.quantityKg || farmer.quantity_kg || farmer.quantity || 0);
    if (qty <= 0) return false;

    // 3. Location validity
    const loc = farmer.location || {};
    const lat = loc.lat ?? loc.latitude;
    const lng = loc.lng ?? loc.longitude;
    if (typeof lat !== "number" || typeof lng !== "number") return false;

    // 4. Quality compatibility (if specified in demand)
    if (buyerDemand.quality && farmer.quality && farmer.quality !== "any") {
      if (buyerDemand.quality.toLowerCase() !== farmer.quality.toLowerCase()) {
        return false;
      }
    }

    return true;
  });
}

// ==============================================================================
// 3. GEOGRAPHIC CLUSTERING
// ==============================================================================

/**
 * Groups nearby compatible farmers into geographic clusters using deterministic proximity.
 *
 * @param {Array} farmers - Filtered compatible farmers
 * @param {number} maxClusterDistanceKm - Configurable cluster threshold (default 25 km)
 * @returns {Array} Array of candidate clusters, each with { clusterId, farmers, totalAvailableKg, centerLat, centerLng }
 */
export function clusterFarmersGeographically(farmers = [], maxClusterDistanceKm = MAX_PICKUP_CLUSTER_DISTANCE_KM) {
  if (!Array.isArray(farmers) || farmers.length === 0) {
    return [];
  }

  const unassigned = [...farmers];
  const clusters = [];
  let clusterIdx = 1;

  while (unassigned.length > 0) {
    // Select seed farmer (anchor)
    const seed = unassigned.shift();
    const seedLoc = seed.location || {};
    const seedLat = seedLoc.lat ?? seedLoc.latitude;
    const seedLng = seedLoc.lng ?? seedLoc.longitude;

    const currentClusterFarmers = [seed];
    const remaining = [];

    for (const other of unassigned) {
      const oLoc = other.location || {};
      const oLat = oLoc.lat ?? oLoc.latitude;
      const oLng = oLoc.lng ?? oLoc.longitude;

      const d = calculateHaversineDistanceKm(seedLat, seedLng, oLat, oLng);
      if (d !== null && d <= maxClusterDistanceKm) {
        currentClusterFarmers.push(other);
      } else {
        remaining.push(other);
      }
    }

    // Compute cluster centroid and aggregate volume
    let sumLat = 0;
    let sumLng = 0;
    let totalKg = 0;

    for (const f of currentClusterFarmers) {
      const loc = f.location || {};
      sumLat += loc.lat ?? loc.latitude;
      sumLng += loc.lng ?? loc.longitude;
      totalKg += Number(f.quantityKg || f.quantity_kg || f.quantity || 0);
    }

    clusters.push({
      clusterId: `cluster_${clusterIdx++}`,
      farmers: currentClusterFarmers,
      totalAvailableKg: totalKg,
      centerLat: Math.round((sumLat / currentClusterFarmers.length) * 10000) / 10000,
      centerLng: Math.round((sumLng / currentClusterFarmers.length) * 10000) / 10000,
      farmerCount: currentClusterFarmers.length
    });

    unassigned.length = 0;
    unassigned.push(...remaining);
  }

  // Sort clusters by highest available quantity first
  clusters.sort((a, b) => b.totalAvailableKg - a.totalAvailableKg);
  return clusters;
}

// ==============================================================================
// 4. DEMAND FULFILLMENT & PARTIAL ALLOCATION
// ==============================================================================

/**
 * Allocates quantities from candidate farmers to satisfy the buyer's requirement exactly.
 * Supports partial allocation so farmers are not over-committed.
 *
 * @param {Array} candidateFarmers - List of farmers in the selected cluster
 * @param {number} demandQuantityKg - Total demand requested by buyer (kg)
 * @returns {Object} { allocatedFarmers, totalAllocatedQuantityKg, remainingUnsatisfiedKg, isFulfilled }
 */
export function matchDemandWithFarmers(candidateFarmers = [], demandQuantityKg = 0) {
  const targetDemand = Number(demandQuantityKg);
  if (isNaN(targetDemand) || targetDemand <= 0 || !Array.isArray(candidateFarmers)) {
    return {
      allocatedFarmers: [],
      totalAllocatedQuantityKg: 0,
      remainingUnsatisfiedKg: targetDemand || 0,
      isFulfilled: false
    };
  }

  let remainingDemand = targetDemand;
  const allocatedFarmers = [];

  for (const farmer of candidateFarmers) {
    if (remainingDemand <= 0) break;

    const availableKg = Number(farmer.quantityKg || farmer.quantity_kg || farmer.quantity || 0);
    if (availableKg <= 0) continue;

    const allocatedKg = Math.min(availableKg, remainingDemand);
    const remainingUnallocatedKg = availableKg - allocatedKg;

    allocatedFarmers.push({
      farmerId: farmer.id || farmer.farmerId || `farmer_${allocatedFarmers.length + 1}`,
      farmerName: farmer.name || farmer.farmerName || `Farmer ${allocatedFarmers.length + 1}`,
      crop: farmer.crop || farmer.crop_type || "Tomato",
      availableQuantityKg: availableKg,
      allocatedQuantityKg: allocatedKg,
      remainingQuantityKg: remainingUnallocatedKg,
      pricePerKg: Number(farmer.pricePerKg || farmer.price_per_kg || farmer.price || 25),
      location: farmer.location,
      phone: farmer.phone || "N/A"
    });

    remainingDemand -= allocatedKg;
  }

  const totalAllocated = targetDemand - remainingDemand;
  const isFulfilled = remainingDemand === 0;

  return {
    allocatedFarmers,
    totalAllocatedQuantityKg: totalAllocated,
    remainingUnsatisfiedKg: Math.max(0, remainingDemand),
    isFulfilled
  };
}

// ==============================================================================
// 5. DRIVER & VEHICLE SELECTION
// ==============================================================================

/**
 * Selects the optimal available vehicle/driver that satisfies load capacity
 * while maximizing capacity utilization (avoids unnecessarily oversized trucks).
 *
 * @param {Array} vehicles - Available vehicle records with attached driver
 * @param {number} totalQuantityKg - Total consolidated load in kg
 * @returns {Object|null} Selected vehicle object with utilization percentage, or null if none fit.
 */
export function selectOptimalVehicle(vehicles = [], totalQuantityKg = 0) {
  if (!Array.isArray(vehicles) || vehicles.length === 0 || totalQuantityKg <= 0) {
    return null;
  }

  // Filter feasible vehicles: capacity >= load and status == AVAILABLE
  const feasible = vehicles.filter((v) => {
    const cap = Number(v.capacityKg || v.capacity || 0);
    const isAvail = !v.status || v.status === DRIVER_STATUS.AVAILABLE;
    return cap >= totalQuantityKg && isAvail;
  });

  if (feasible.length === 0) {
    return null;
  }

  // Sort by smallest excess capacity (highest utilization)
  feasible.sort((a, b) => {
    const capA = Number(a.capacityKg || a.capacity || 0);
    const capB = Number(b.capacityKg || b.capacity || 0);
    return capA - capB;
  });

  const selected = feasible[0];
  const cap = Number(selected.capacityKg || selected.capacity || 0);
  const utilization = Math.round((totalQuantityKg / cap) * 10000) / 100; // e.g. 83.33%

  return {
    ...selected,
    vehicleCapacityKg: cap,
    vehicleUtilizationPercent: utilization
  };
}

// ==============================================================================
// 6. ROUTE GENERATION (NEAREST-NEIGHBOUR ESTIMATED ROUTE)
// ==============================================================================

/**
 * Builds a deterministic route starting at the driver's location, visiting all pickup farmers
 * using nearest-neighbour order, and finishing at the buyer's delivery point.
 *
 * @param {Object} driverLocation - Driver start { lat, lng, address }
 * @param {Array} allocatedFarmers - List of allocated farmer objects
 * @param {Object} buyerLocation - Buyer delivery location { lat, lng, address }
 * @returns {Object} Route object with stops, leg distances, and total estimated distance.
 */
export function buildConsolidatedRoute(driverLocation, allocatedFarmers = [], buyerLocation) {
  if (!driverLocation || !buyerLocation || !Array.isArray(allocatedFarmers) || allocatedFarmers.length === 0) {
    return {
      stops: [],
      totalEstimatedDistanceKm: 0,
      legs: []
    };
  }

  const dLat = driverLocation.lat ?? driverLocation.latitude;
  const dLng = driverLocation.lng ?? driverLocation.longitude;

  // Support single buyer or array of multiple buyers
  const buyerList = Array.isArray(buyerLocation) 
    ? buyerLocation 
    : [buyerLocation];

  const unvisitedFarmers = [...allocatedFarmers];
  const unvisitedBuyers = [...buyerList];
  const stops = [];
  const legs = [];

  const totalCargoKg = allocatedFarmers.reduce((sum, f) => sum + (Number(f.allocatedQuantityKg) || 0), 0);
  let currentCargoKg = 0;

  // Stop 0: Driver Start
  stops.push({
    stopIndex: 0,
    stopType: "DRIVER_START",
    name: "Driver Starting Location",
    location: driverLocation,
    coordinates: { lat: dLat, lng: dLng },
    quantityKg: 0,
    cumulativeLoadKg: 0,
    estimatedDistanceToNextKm: 0
  });

  let currentLat = dLat;
  let currentLng = dLng;
  let totalDistanceKm = 0;

  // 1. Visit all farmers in nearest-neighbour order
  while (unvisitedFarmers.length > 0) {
    let nearestIdx = 0;
    let minDistance = Infinity;

    for (let i = 0; i < unvisitedFarmers.length; i++) {
      const f = unvisitedFarmers[i];
      const loc = f.location || f.pickupCoordinates || {};
      const fLat = loc.lat ?? loc.latitude;
      const fLng = loc.lng ?? loc.longitude;

      const dist = calculateHaversineDistanceKm(currentLat, currentLng, fLat, fLng);
      if (dist !== null && dist < minDistance) {
        minDistance = dist;
        nearestIdx = i;
      }
    }

    const nextFarmer = unvisitedFarmers.splice(nearestIdx, 1)[0];
    const nextLoc = nextFarmer.location || nextFarmer.pickupCoordinates || {};
    const nextLat = nextLoc.lat ?? nextLoc.latitude;
    const nextLng = nextLoc.lng ?? nextLoc.longitude;

    const legDist = Math.round(minDistance * 100) / 100;
    totalDistanceKm += legDist;
    currentCargoKg += (Number(nextFarmer.allocatedQuantityKg) || 0);

    legs.push({
      fromStop: stops[stops.length - 1].name,
      toStop: `Pickup: ${nextFarmer.farmerName}`,
      distanceKm: legDist
    });

    stops[stops.length - 1].estimatedDistanceToNextKm = legDist;

    stops.push({
      stopIndex: stops.length,
      stopType: "PICKUP",
      id: nextFarmer.farmerId,
      farmerId: nextFarmer.farmerId,
      name: `Pickup: ${nextFarmer.farmerName}`,
      farmerName: nextFarmer.farmerName,
      crop: nextFarmer.crop,
      quantityKg: nextFarmer.allocatedQuantityKg,
      cumulativeLoadKg: currentCargoKg,
      coordinates: { lat: nextLat, lng: nextLng },
      location: nextLoc,
      status: "PENDING",
      estimatedDistanceToNextKm: 0
    });

    currentLat = nextLat;
    currentLng = nextLng;
  }

  // 2. Deliver to all buyers in nearest-neighbour order
  while (unvisitedBuyers.length > 0) {
    let nearestBuyerIdx = 0;
    let minBuyerDist = Infinity;

    for (let i = 0; i < unvisitedBuyers.length; i++) {
      const b = unvisitedBuyers[i];
      const bLoc = b.deliveryLocation || b.deliveryCoordinates || b.location || b;
      const bLat = bLoc.lat ?? bLoc.latitude;
      const bLng = bLoc.lng ?? bLoc.longitude;

      const dist = calculateHaversineDistanceKm(currentLat, currentLng, bLat, bLng);
      if (dist !== null && dist < minBuyerDist) {
        minBuyerDist = dist;
        nearestBuyerIdx = i;
      }
    }

    const nextBuyer = unvisitedBuyers.splice(nearestBuyerIdx, 1)[0];
    const bLoc = nextBuyer.deliveryLocation || nextBuyer.deliveryCoordinates || nextBuyer.location || nextBuyer;
    const bLat = bLoc.lat ?? bLoc.latitude;
    const bLng = bLoc.lng ?? bLoc.longitude;

    const legDist = Math.round(minBuyerDist * 100) / 100;
    totalDistanceKm += legDist;
    const buyerDropQty = Number(nextBuyer.quantityKg || nextBuyer.quantityRequiredKg || currentCargoKg);
    currentCargoKg = Math.max(0, currentCargoKg - buyerDropQty);

    legs.push({
      fromStop: stops[stops.length - 1].name,
      toStop: `Delivery: ${nextBuyer.buyerName || nextBuyer.businessName || "Buyer Facility"}`,
      distanceKm: legDist
    });

    stops[stops.length - 1].estimatedDistanceToNextKm = legDist;

    stops.push({
      stopIndex: stops.length,
      stopType: "DELIVERY",
      id: nextBuyer.buyerId || nextBuyer.id,
      buyerId: nextBuyer.buyerId || nextBuyer.id,
      name: `Delivery: ${nextBuyer.buyerName || nextBuyer.businessName || "Buyer Facility"}`,
      buyerName: nextBuyer.buyerName || nextBuyer.businessName || "Buyer Facility",
      quantityKg: buyerDropQty,
      cumulativeLoadKg: currentCargoKg,
      coordinates: { lat: bLat, lng: bLng },
      location: bLoc,
      status: "PENDING",
      estimatedDistanceToNextKm: 0
    });

    currentLat = bLat;
    currentLng = bLng;
  }

  return {
    stops,
    legs,
    totalStops: stops.length,
    totalEstimatedDistanceKm: Math.round(totalDistanceKm * 100) / 100
  };
}

// ==============================================================================
// 7. TRANSPORT COST & PROPORTIONAL ALLOCATION
// ==============================================================================

/**
 * Calculates estimated transport cost based on route distance and rate per km.
 *
 * @param {number} estimatedDistanceKm - Total route distance
 * @param {number} ratePerKm - Configurable rate per km (default ₹60/km)
 * @returns {number} Total estimated transport cost in ₹
 */
export function calculateTransportCost(estimatedDistanceKm = 0, ratePerKm = DEFAULT_TRANSPORT_RATE_PER_KM) {
  const dist = Number(estimatedDistanceKm) || 0;
  const rate = Number(ratePerKm) || DEFAULT_TRANSPORT_RATE_PER_KM;
  return Math.round(dist * rate * 100) / 100;
}

/**
 * Calculates transport cost per kg.
 *
 * @param {number} totalTransportCost - Total transport cost (₹)
 * @param {number} totalQuantityKg - Total shipment quantity (kg)
 * @returns {number} Transport cost per kg (₹/kg)
 */
export function calculateTransportCostPerKg(totalTransportCost = 0, totalQuantityKg = 0) {
  const cost = Number(totalTransportCost) || 0;
  const qty = Number(totalQuantityKg) || 0;
  if (qty <= 0) return 0;
  return Math.round((cost / qty) * 10000) / 10000;
}

/**
 * Distributes the total transport cost proportionally across farmers based on allocated quantity.
 * Applies exact floating-point sum correction so the sum of farmer shares exactly equals totalTransportCost.
 *
 * @param {Array} allocatedFarmers - List of allocated farmer objects
 * @param {number} totalTransportCost - Total transport cost (₹)
 * @param {number} totalQuantityKg - Total shipment quantity (kg)
 * @returns {Array} Allocated farmers with exact transportShare field
 */
export function allocateTransportCostToFarmers(allocatedFarmers = [], totalTransportCost = 0, totalQuantityKg = 0) {
  if (!Array.isArray(allocatedFarmers) || allocatedFarmers.length === 0 || totalQuantityKg <= 0) {
    return [];
  }

  const cost = Number(totalTransportCost) || 0;
  const totalQty = Number(totalQuantityKg) || 1;

  let assignedSum = 0;
  const withShares = allocatedFarmers.map((f) => {
    const proportion = f.allocatedQuantityKg / totalQty;
    const share = Math.round(cost * proportion * 100) / 100;
    assignedSum += share;
    return {
      ...f,
      transportShare: share,
      transportSharePerKg: Math.round((share / f.allocatedQuantityKg) * 10000) / 10000
    };
  });

  // Floating-point rounding correction: adjust difference onto the farmer with the largest share
  const diff = Math.round((cost - assignedSum) * 100) / 100;
  if (Math.abs(diff) > 0 && withShares.length > 0) {
    let maxIdx = 0;
    let maxAlloc = -1;
    for (let i = 0; i < withShares.length; i++) {
      if (withShares[i].allocatedQuantityKg > maxAlloc) {
        maxAlloc = withShares[i].allocatedQuantityKg;
        maxIdx = i;
      }
    }
    withShares[maxIdx].transportShare = Math.round((withShares[maxIdx].transportShare + diff) * 100) / 100;
  }

  return withShares;
}

// ==============================================================================
// 8. FARMER NET EXPECTED VALUE CALCULATION
// ==============================================================================

/**
 * Calculates each farmer's estimated Gross Revenue, Expected Losses, and Net Expected Value.
 *
 * Formula:
 * Gross Revenue = Agreed Price/kg × Allocated Qty
 * Net Expected Value = Gross Revenue - Transport Share - Expected Shrinkage Loss - Expected Rejection Loss - Platform Fee
 *
 * @param {Object} farmerAllocation - Farmer allocation with allocatedQuantityKg and transportShare
 * @param {number} agreedPricePerKg - Agreed price per kg (₹)
 * @param {number} transportShare - Farmer's allocated transport share (₹)
 * @param {Object} [lossOptions] - Optional loss parameters
 * @param {number} [lossOptions.shrinkageRate=0.015] - Estimated transit shrinkage loss (e.g. 1.5%)
 * @param {number} [lossOptions.rejectionProbability=0.01] - Estimated rejection risk (e.g. 1.0%)
 * @param {number} [lossOptions.platformFee=0] - Optional platform fee
 * @returns {Object} Complete Net Expected Value breakdown
 */
export function calculateFarmerNetExpectedValue(
  farmerAllocation,
  agreedPricePerKg = 0,
  transportShare = 0,
  lossOptions = {}
) {
  const qty = Number(farmerAllocation?.allocatedQuantityKg || 0);
  const price = Number(agreedPricePerKg || farmerAllocation?.pricePerKg || 0);
  const transport = Number(transportShare ?? farmerAllocation?.transportShare ?? 0);

  const shrinkageRate = Number(lossOptions.shrinkageRate ?? 0.015); // 1.5% default transit moisture/shrinkage
  const rejectionProb = Number(lossOptions.rejectionProbability ?? 0.01); // 1.0% default quality rejection probability
  const platformFee = Number(lossOptions.platformFee ?? 0);

  const grossRevenue = Math.round(price * qty * 100) / 100;
  const expectedShrinkageLoss = Math.round(grossRevenue * shrinkageRate * 100) / 100;
  const expectedRejectionLoss = Math.round(grossRevenue * rejectionProb * 100) / 100;
  const totalExpectedLosses = Math.round((expectedShrinkageLoss + expectedRejectionLoss) * 100) / 100;

  const netExpectedValue = Math.round((grossRevenue - transport - totalExpectedLosses - platformFee) * 100) / 100;
  const netRealizedPerKg = qty > 0 ? Math.round((netExpectedValue / qty) * 100) / 100 : 0;

  return {
    farmerId: farmerAllocation?.farmerId,
    farmerName: farmerAllocation?.farmerName,
    crop: farmerAllocation?.crop,
    allocatedQuantityKg: qty,
    pricePerKg: price,
    grossRevenue,
    transportShare: transport,
    expectedShrinkageLoss,
    expectedRejectionLoss,
    totalExpectedLosses,
    platformFee,
    netExpectedValue,
    netRealizedPerKg
  };
}

// ==============================================================================
// 9. MASTER CONSOLIDATION ENGINE
// ==============================================================================

/**
 * Master deterministic logistics consolidation pipeline.
 *
 * @param {Object} params
 * @param {Object} params.buyerDemand - { crop, quantityRequiredKg, targetPrice, deliveryLocation }
 * @param {Array} params.farmers - Available farmer produce listings
 * @param {Array} params.drivers - Available drivers
 * @param {Array} params.vehicles - Available vehicles with capacityKg and driver info
 * @param {Object} [params.config] - Optional overrides (maxClusterDistanceKm, transportRatePerKm)
 * @returns {Object} Consolidation result { success, shipment, errorReason, cluster }
 */
export function consolidateSmartShipment({
  buyerDemand,
  farmers = [],
  drivers = [],
  vehicles = [],
  config = {}
} = {}) {
  const maxClusterDist = config.maxClusterDistanceKm || MAX_PICKUP_CLUSTER_DISTANCE_KM;
  const ratePerKm = config.transportRatePerKm || DEFAULT_TRANSPORT_RATE_PER_KM;

  if (!buyerDemand || !buyerDemand.crop || !buyerDemand.quantityRequiredKg) {
    return {
      success: false,
      errorReason: "Invalid buyer demand specification. Crop and quantity required are mandatory."
    };
  }

  const demandKg = Number(buyerDemand.quantityRequiredKg);
  const targetPrice = Number(buyerDemand.targetPrice || 28);
  const buyerLoc = buyerDemand.deliveryLocation || {
    lat: 9.9195,
    lng: 78.1217,
    city: "Madurai",
    district: "Madurai",
    state: "Tamil Nadu",
    businessName: buyerDemand.businessName || "Vaigai Food Processors"
  };

  // 1. Filter compatible farmers
  const compatibleFarmers = filterCompatibleFarmers(farmers, buyerDemand);
  if (compatibleFarmers.length === 0) {
    return {
      success: false,
      errorReason: `No compatible farmers found with available "${buyerDemand.crop}" stock.`
    };
  }

  // 2. Geographic clustering
  const clusters = clusterFarmersGeographically(compatibleFarmers, maxClusterDist);
  if (clusters.length === 0) {
    return {
      success: false,
      errorReason: `No geographic clusters of farmers found within ${maxClusterDist} km threshold.`
    };
  }

  // Pick best cluster (highest volume)
  const bestCluster = clusters[0];

  // 3. Demand fulfillment & partial allocation
  const fulfillment = matchDemandWithFarmers(bestCluster.farmers, demandKg);
  if (fulfillment.allocatedFarmers.length === 0) {
    return {
      success: false,
      errorReason: "Could not allocate produce from cluster farmers to satisfy requirement."
    };
  }

  const totalConsolidatedKg = fulfillment.totalAllocatedQuantityKg;

  // 4. Vehicle & Driver selection
  const optimalVehicle = selectOptimalVehicle(vehicles, totalConsolidatedKg);
  if (!optimalVehicle) {
    const maxAvailCapacity = vehicles.reduce((max, v) => Math.max(max, Number(v.capacityKg || 0)), 0);
    return {
      success: false,
      errorReason: `No available vehicle has sufficient capacity for ${totalConsolidatedKg.toLocaleString()} kg. (Maximum available vehicle capacity is ${maxAvailCapacity.toLocaleString()} kg).`,
      requiredQuantityKg: totalConsolidatedKg,
      maxAvailableCapacityKg: maxAvailCapacity
    };
  }

  // Resolve driver info
  const driver = drivers.find((d) => d.driverId === optimalVehicle.driverId) || {
    driverId: optimalVehicle.driverId || "drv_ravi",
    name: optimalVehicle.driverName || "Ravi",
    phone: "9876543290",
    location: optimalVehicle.currentLocation || { lat: 9.9280, lng: 78.1150, address: "Madurai Logistics Hub" }
  };

  const driverStartLoc = driver.location || { lat: 9.9280, lng: 78.1150, address: "Madurai Logistics Hub" };

  // 5. Route generation (Nearest Neighbour)
  const route = buildConsolidatedRoute(driverStartLoc, fulfillment.allocatedFarmers, buyerLoc);

  // 6. Transport cost calculation
  const totalTransportCost = calculateTransportCost(route.totalEstimatedDistanceKm, ratePerKm);
  const transportCostPerKg = calculateTransportCostPerKg(totalTransportCost, totalConsolidatedKg);

  // 7. Proportional transport share allocation to farmers
  const allocatedFarmersWithShares = allocateTransportCostToFarmers(
    fulfillment.allocatedFarmers,
    totalTransportCost,
    totalConsolidatedKg
  );

  // 8. Net Expected Value calculations
  const netValueBreakdowns = allocatedFarmersWithShares.map((f) =>
    calculateFarmerNetExpectedValue(f, targetPrice, f.transportShare)
  );

  // 9. Construct Final Shipment Record
  const shipmentId = `shipment_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
  const shipment = {
    shipmentId,
    buyerId: buyerDemand.buyerId || "usr_buyer_vaigai",
    buyerName: buyerDemand.businessName || "Vaigai Food Processors",
    crop: buyerDemand.crop,
    demandQuantityKg: demandKg,
    totalQuantityKg: totalConsolidatedKg,
    isFullyFulfilled: fulfillment.isFulfilled,
    farmerAllocations: allocatedFarmersWithShares,
    netValueBreakdowns,
    driverId: driver.driverId,
    driverName: driver.name,
    driverPhone: driver.phone,
    vehicleId: optimalVehicle.vehicleId,
    vehicleType: optimalVehicle.vehicleType || VEHICLE_TYPES.HEAVY_TRUCK,
    vehicleCapacityKg: optimalVehicle.vehicleCapacityKg,
    vehicleUtilizationPercent: optimalVehicle.vehicleUtilizationPercent,
    estimatedDistanceKm: route.totalEstimatedDistanceKm,
    estimatedTransportCost: totalTransportCost,
    transportRatePerKm: ratePerKm,
    transportCostPerKg: transportCostPerKg,
    route,
    currentStopIndex: 0,
    status: SHIPMENT_STATUS.MATCHED,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };

  return {
    success: true,
    shipment,
    cluster: bestCluster
  };
}

// ==============================================================================
// 10. SHIPMENT STATE MACHINE & DRIVER WORKFLOW
// ==============================================================================

const VALID_TRANSITIONS = {
  [SHIPMENT_STATUS.MATCHED]: [SHIPMENT_STATUS.DRIVER_ASSIGNED, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.DRIVER_ASSIGNED]: [SHIPMENT_STATUS.READY_FOR_PICKUP, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.READY_FOR_PICKUP]: [SHIPMENT_STATUS.IN_TRANSIT, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.IN_TRANSIT]: [SHIPMENT_STATUS.DELIVERED, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.DELIVERED]: [],
  [SHIPMENT_STATUS.CANCELLED]: []
};

/**
 * Executes a verified state transition on a shipment.
 *
 * @param {Object} shipment - Active shipment record
 * @param {string} nextStatus - Next target status
 * @param {Object} [metadata] - Optional metadata updates (e.g. currentStopIndex, notes)
 * @returns {Object} Updated shipment or throws Error if invalid transition
 */
export function transitionShipmentStatus(shipment, nextStatus, metadata = {}) {
  if (!shipment || !shipment.status) {
    throw new Error("Invalid shipment object.");
  }

  const allowed = VALID_TRANSITIONS[shipment.status] || [];
  if (!allowed.includes(nextStatus)) {
    throw new Error(`Invalid shipment state transition from "${shipment.status}" to "${nextStatus}".`);
  }

  const updated = {
    ...shipment,
    ...metadata,
    status: nextStatus,
    updatedAt: new Date().toISOString()
  };

  // Persist update in localDB & IndexedDB
  saveShipment(updated);

  // Enqueue offline sync action
  enqueueAction({
    userId: shipment.driverId || "system",
    actionType: ACTION_TYPES.UPDATE_LOGISTICS_SHIPMENT_STATUS,
    entityType: "logisticsShipments",
    entityId: updated.shipmentId,
    payload: updated
  }).catch(() => {});

  return updated;
}

// ==============================================================================
// 11. STORAGE & PERSISTENCE HELPERS
// ==============================================================================

export function getShipments() {
  return localDB.getData(KEYS.LOGISTICS_SHIPMENTS) || [];
}

export function getShipmentById(shipmentId) {
  const shipments = getShipments();
  return shipments.find((s) => s.shipmentId === shipmentId) || null;
}

export function saveShipment(shipment) {
  if (!shipment || !shipment.shipmentId) return;
  const existing = getShipments();
  const idx = existing.findIndex((s) => s.shipmentId === shipment.shipmentId);
  if (idx >= 0) {
    existing[idx] = shipment;
    localDB.saveData(KEYS.LOGISTICS_SHIPMENTS, existing);
  } else {
    localDB.saveData(KEYS.LOGISTICS_SHIPMENTS, [shipment, ...existing]);
  }
}

// ==============================================================================
// 12. DETERMINISTIC DEMO & TEST DATASET
// ==============================================================================

export const DEMO_FARMERS = [
  {
    id: "farmer_a_ramu",
    name: "Farmer A (Ramu)",
    crop: "Tomato",
    quantityKg: 1000,
    pricePerKg: 28,
    location: { lat: 9.9412, lng: 78.1385, address: "Madurai East Farm" },
    phone: "9876543201",
    quality: "fresh_market_grade"
  },
  {
    id: "farmer_b_murugan",
    name: "Farmer B (Murugan)",
    crop: "Tomato",
    quantityKg: 1000,
    pricePerKg: 28,
    location: { lat: 9.9620, lng: 78.1490, address: "Alagar Kovil Road" },
    phone: "9876543202",
    quality: "fresh_market_grade"
  },
  {
    id: "farmer_c_ganesan",
    name: "Farmer C (Ganesan)",
    crop: "Tomato",
    quantityKg: 2000,
    pricePerKg: 27,
    location: { lat: 9.9550, lng: 78.1620, address: "Othakadai Agricultural Field" },
    phone: "9876543203",
    quality: "fresh_market_grade"
  },
  {
    id: "farmer_d_karthik",
    name: "Farmer D (Karthik)",
    crop: "Tomato",
    quantityKg: 3000,
    pricePerKg: 27,
    location: { lat: 10.0120, lng: 78.3300, address: "Melur Agricultural Cluster East" },
    phone: "9876543204",
    quality: "fresh_market_grade"
  },
  {
    id: "farmer_e_sundaram",
    name: "Farmer E (Sundaram)",
    crop: "Tomato",
    quantityKg: 3000,
    pricePerKg: 28,
    location: { lat: 9.9980, lng: 78.2950, address: "Melur West Farm Sector" },
    phone: "9876543205",
    quality: "fresh_market_grade"
  }
];

export const DEMO_BUYER = {
  buyerId: "usr_buyer_vaigai_food",
  businessName: "Vaigai Agro Food Processors Ltd.",
  businessType: "Processing Unit",
  crop: "Tomato",
  quantityRequiredKg: 10000, // 10 Tons
  targetPrice: 28,
  deliveryLocation: {
    lat: 9.9195,
    lng: 78.1217,
    address: "Madurai Central Food Processing Hub",
    city: "Madurai",
    district: "Madurai",
    state: "Tamil Nadu"
  }
};

export const DEMO_DRIVERS_AND_VEHICLES = {
  drivers: [
    {
      driverId: "drv_ravi",
      name: "Ravi",
      phone: "9876543290",
      status: DRIVER_STATUS.AVAILABLE,
      location: { lat: 9.9280, lng: 78.1150, address: "Madurai Logistics Ring Road Depot" }
    },
    {
      driverId: "drv_kumar",
      name: "Kumar",
      phone: "9876543291",
      status: DRIVER_STATUS.AVAILABLE,
      location: { lat: 10.0800, lng: 77.9600, address: "Vadipatti Transport Depot" }
    },
    {
      driverId: "drv_suresh",
      name: "Suresh",
      phone: "9876543292",
      status: DRIVER_STATUS.AVAILABLE,
      location: { lat: 10.0100, lng: 77.4700, address: "Theni Goods Hub" }
    }
  ],
  vehicles: [
    {
      vehicleId: "veh_truck_12t_01",
      driverId: "drv_ravi",
      driverName: "Ravi",
      vehicleType: VEHICLE_TYPES.HEAVY_TRUCK,
      capacityKg: 12000, // 12 Tons
      ratePerKm: 60,
      status: DRIVER_STATUS.AVAILABLE,
      currentLocation: { lat: 9.9280, lng: 78.1150, address: "Madurai Logistics Ring Road Depot" }
    },
    {
      vehicleId: "veh_truck_5t_01",
      driverId: "drv_kumar",
      driverName: "Kumar",
      vehicleType: VEHICLE_TYPES.MEDIUM_TRUCK,
      capacityKg: 5000, // 5 Tons
      ratePerKm: 45,
      status: DRIVER_STATUS.AVAILABLE,
      currentLocation: { lat: 10.0800, lng: 77.9600, address: "Vadipatti Transport Depot" }
    },
    {
      vehicleId: "veh_pickup_2t_01",
      driverId: "drv_suresh",
      driverName: "Suresh",
      vehicleType: VEHICLE_TYPES.SMALL_PICKUP,
      capacityKg: 2000, // 2 Tons
      ratePerKm: 30,
      status: DRIVER_STATUS.AVAILABLE,
      currentLocation: { lat: 10.0100, lng: 77.4700, address: "Theni Goods Hub" }
    }
  ]
};

export function initializeLogisticsSeedData() {
  const existingShipments = getShipments();
  if (existingShipments.length === 0) {
    // Generate initial consolidated demo shipment
    const result = consolidateSmartShipment({
      buyerDemand: DEMO_BUYER,
      farmers: DEMO_FARMERS,
      drivers: DEMO_DRIVERS_AND_VEHICLES.drivers,
      vehicles: DEMO_DRIVERS_AND_VEHICLES.vehicles
    });
    if (result.success) {
      saveShipment(result.shipment);
    }
  }
}

const BACKEND_BASE_URL = (typeof import.meta !== 'undefined' && import.meta.env && import.meta.env.VITE_BACKEND_URL) || 'http://localhost:5000/api/v1';

/**
 * Persists a consolidated shipment to the backend PostgreSQL database
 */
export async function syncShipmentToBackend(shipment, user) {
  if (!shipment) return null;
  const userId = user?.userId || user?.id || 'system';
  const role = user?.role || user?.activeRole || 'farmer';

  try {
    const res = await fetch(`${BACKEND_BASE_URL}/logistics/shipments`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-user-id': userId,
        'x-user-role': role,
        'Authorization': `Bearer ${userId}`
      },
      body: JSON.stringify(shipment)
    });

    if (res.ok) {
      const data = await res.json();
      return data.data;
    }
  } catch (err) {
    console.warn('[Logistics Backend Sync Warning]', err.message);
  }
  return null;
}

/**
 * Updates shipment status in backend with real-time socket broadcast
 */
export async function updateShipmentStatusWithBackend(shipmentId, nextStatus, user) {
  const userId = user?.userId || user?.id || 'system';
  const role = user?.role || user?.activeRole || 'driver';

  try {
    const res = await fetch(`${BACKEND_BASE_URL}/shipments/${shipmentId}/status`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        'x-user-id': userId,
        'x-user-role': role,
        'Authorization': `Bearer ${userId}`
      },
      body: JSON.stringify({ status: nextStatus })
    });

    if (res.ok) {
      const data = await res.json();
      return data.data;
    }
  } catch (err) {
    console.warn('[Logistics Status Update Warning]', err.message);
  }
  return null;
}

/**
 * Updates stop progress in backend with real-time socket broadcast
 */
export async function updateStopStatusWithBackend(shipmentId, stopIndex, stopStatus, user) {
  const userId = user?.userId || user?.id || 'system';
  const role = user?.role || user?.activeRole || 'driver';

  try {
    const res = await fetch(`${BACKEND_BASE_URL}/shipments/${shipmentId}/stops/${stopIndex}`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        'x-user-id': userId,
        'x-user-role': role,
        'Authorization': `Bearer ${userId}`
      },
      body: JSON.stringify({ status: stopStatus })
    });

    if (res.ok) {
      const data = await res.json();
      return data.data;
    }
  } catch (err) {
    console.warn('[Logistics Stop Update Warning]', err.message);
  }
  return null;
}

/**
 * Fetches privacy-sanitized live tracking from backend for Farmer / Buyer
 */
export async function fetchRemoteTracking(shipmentId, user) {
  const userId = user?.userId || user?.id || 'system';
  const role = user?.role || user?.activeRole || 'farmer';

  try {
    const res = await fetch(`${BACKEND_BASE_URL}/shipments/${shipmentId}/tracking`, {
      headers: {
        'x-user-id': userId,
        'x-user-role': role,
        'Authorization': `Bearer ${userId}`
      }
    });

    if (res.ok) {
      const data = await res.json();
      return data.data;
    }
  } catch (err) {
    console.warn('[Logistics Tracking Fetch Warning]', err.message);
  }
  return null;
}
